// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFlFP8_4T97uNUfs1qblYdQMGkDvFgfTg',
    appId: '1:646014830947:web:1de701e802ddf3566beb56',
    messagingSenderId: '646014830947',
    projectId: 'gestion-financiere-48899',
    authDomain: 'gestion-financiere-48899.firebaseapp.com',
    storageBucket: 'gestion-financiere-48899.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiTVlu5Q9y9h-aSyeQlPh8cFeSMN7bIzI',
    appId: '1:646014830947:android:f9715ea9fc0698a46beb56',
    messagingSenderId: '646014830947',
    projectId: 'gestion-financiere-48899',
    storageBucket: 'gestion-financiere-48899.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQC_rvroj87eClB4-FfQQzVP0LU_xHVog',
    appId: '1:646014830947:ios:f36077b4b93fffbb6beb56',
    messagingSenderId: '646014830947',
    projectId: 'gestion-financiere-48899',
    storageBucket: 'gestion-financiere-48899.firebasestorage.app',
    iosBundleId: 'com.example.gestionFinanciere',
  );
}
